export interface Ibook {
    id: String,
    title: String,
    author: String,
    initialPrice: number,
    priceAfterReduction: number,
    smallReduction: number,
    bigReduction: number,
    changeablePrice: number,
    currencyCode: String,
    identifier: number,
    categories: Array<String>,
    description: String,
    language: String,
    thumbnail: String,
    averageRating: number,
    pageCount: String,
    isEbook: Boolean,
    isInCart: Boolean,
    numberOfBooks: number,
    hidden: Boolean,
}